server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory_db
    username: inventory_user
    password: inventory_pass
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
