server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/payment_db
    username: payment_user
    password: payment_pass
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  demo:
    username: alexjoy
    password: change-me
  jwt:
    secret: YWxleGpveS1vcmRlci1wbGF0Zm9ybS1zZWNyZXQta2V5LTEyMzQ1Njc4OTA=
    expiration-seconds: 3600
