server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/payment_db}
    username: ${DB_USERNAME:payment_user}
    password: ${DB_PASSWORD:payment_pass}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  demo:
    username: ${DEMO_USERNAME:alexjoy}
    password: ${DEMO_PASSWORD:change-me}
  jwt:
    secret: ${JWT_SECRET:alexjoy-order-platform-secret-key-1234567890-super}
    expiration-seconds: ${JWT_EXP_SECONDS:3600}
