server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/order_db}
    username: ${DB_USERNAME:order_user}
    password: ${DB_PASSWORD:order_pass}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true

client:
  inventory:
    base-url: ${INVENTORY_BASE_URL:http://localhost:8081}
  payment:
    base-url: ${PAYMENT_BASE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  demo:
    username: ${DEMO_USERNAME:alexjoy}
    password: ${DEMO_PASSWORD:change-me}
  jwt:
    secret: ${JWT_SECRET:alexjoy-order-platform-secret-key-1234567890-super}
    expiration-seconds: ${JWT_EXP_SECONDS:3600}
  internal-client:
    subject: ${INTERNAL_CLIENT_SUBJECT:order-service}
