server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: order_user
    password: order_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

client:
  inventory:
    base-url: http://localhost:8081
  payment:
    base-url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  demo:
    username: alexjoy
    password: change-me
  jwt:
    secret: YWxleGpveS1vcmRlci1wbGF0Zm9ybS1zZWNyZXQta2V5LTEyMzQ1Njc4OTA=
    expiration-seconds: 3600
  internal-client:
    subject: order-service
